### ISSUE TITLE
Expose `popperOptions` type

### ISSUE THREAD

**Issue by SimonSchick** [magicbell-io/magicbell-react#15]
https://github.com/magicbell-io/magicbell-react/blob/90db2ef28a524b6192d424890456cbd56c637cd2/src/components/FloatingNotificationInbox/FloatingNotificationInbox.tsx#L18

Trying to increase the distance between button and inbox, kinda annoying to do with those types being implicitly any.

**Comment by smeijer** [comment]
Yeah, that should be changed. Do you wish to submit a pull request?
