### ISSUE TITLE
[RFC]: Plans for v9

### ISSUE THREAD

**Issue by smeijer** [magicbell-io/magicbell-react#18]
## Intro

This writing describes the high level of changes that I believe we should prioritize in the near- to medium-term future. I aim to update this opening post with changes as they appear.

These are my current thoughts. I welcome everyone to contribute and let us hear your ideas on how we can make things better.

## Abstractions

The current minimal implementation involves specifying the inbox as a render function. I think we can simplify this further, in a way that the minimal implementation would be a single component, which defaults to the floating inbox:

```jsx
<MagicBell apiKey={apiKey} userEmail={userEmail} />
```

## Styles & Customizability

To be able to give the consumer full control over the elements we expose, we should do a number of different things:

- `forwardRef` on every component, so that the consumer has full control over the elements we render.
- forward all props to the underlying element, so consumers can provide `className`, `style` attributes, event handlers, or anything they'd like.
- wrap event handlers, so that consumers can `preventDefault` and/or provide additional handlers
- support the `as` prop so the consumer can provide styled-components
- use CSS selectors with the lowest possible specificity score, and [`classer`](https://github.com/code-hike/codehike/tree/next/packages/classer) to merge in consumer-level classNames.

By not supporting anything specific, we support everything:

```jsx
// custom className
<NotificationItem className="text-lg border-red-500" />

// style attribute
<NotificationItem style={{ fontSize: '2rem' }} />

// emotion
<NotificationItem css={css`fontSize: 2rem`} />

// styled components
const StyledNotification = styled(NotificationItem)`
  font-size: 2rem;
`

// classer
<MagicBell classes={{
  'magicbell-notification-item': 'my-notification',
  'magicbell-notification-badge': 'text-lg border-red-500',
}} />
```

## Accessibility

Being accessible (with keyboard and screen readers) should be our priority. This involves:

- use the proper elements,  think `<button>` instead of `<a>`. 
- use CSS transforms to uppercase text, not uppercase the string itself, as that may cause screen readers to SCREAM instead of politely pronounce.
- add missing `aria-` attributes to inform screen readers about the changes made to the DOM (new notification, inbox open/closed, ...)
- make sure that the inbox can be navigated with the keyboard
- add focus styles to support keyboard navigation

## Packages

- We should republish `@magicbell/magicbell-react` as `@magicbell/react`, while we turn `@magicbell/magicbell-react` into a small wrapper with an update notice.
- We might want to sync the version numbers of `@magicbell/magicbell-react` and `@magicbell/embeddable`

## Open Questions

- **Theming**
  We currently support a `theme` object, that is used to style elements using emotion. Should we maintain backward compatibility? We can use CSS vars in our new standard CSS file, and then map the theme to CSS vars. But I'm not sure how feasible that is. Thoughts?

- **public/private API separation**
  Some components are meant to be used by consumers. Others are more private and meant to be used by our components alone. How are we going to separate this? We need the freedom to refactor internal/private components, without the need to introduce a "breaking change", because someone might be using it. Things that come to mind:
  - move private components to a `/private` folder, the name should make the intent clear
  - keep child components in the same file as the pubic component, just don't export them. Every exported component is public.
  - use the `package.json#exports` field to declare the public API, options:
	  - add all public explores explicitly
	  - create a `/public` folder that re-exports some components from `/components`, and simply add an export pattern to package.json: `"exports": { "./*": "./src/public/*.js" }`. `/public` might be confusing with the `/public` folder for web assets though.

**Comment by pavanjadhaw** [comment]
Hey @smeijer, would love to help with this

**Comment by SimonSchick** [comment]
What would be interesting is a minimal API that only provides the unread count (and maybe others), this would allow lazy loading the bulk of the SDK until it's actually required.

Unsure if this is a little bit of a unique requirement though.

**Comment by smeijer** [comment]
@pavanjadhaw , thanks for the offer!

@SimonSchick, that's a great idea! I'm not sure how much there is to gain, but it's certainly worth looking into.

**Comment by josuemontano** [comment]
@SimonSchick I think you can use the `MagicBellProvider` component for that end. It is possible to wrap the `MagicBell` component with it:

```jsx
<MagicBellProvider apiKey="[API_KEY]" userEmail="[USER_EMAIL]">
  {condition ? <MagicBell /> : null}
  <App />
</MagicBellProvider>
```

this allow you to fetch data you need at `App`.

**Comment by smeijer** [comment]
Closing this issue, as we'll be tracking the work in linear. All kinds of feedback is still more than welcome :)
